name: 'publish-docker-image'
description: ''
inputs:
  repository:
    description: ''
    required: false
    default: ghcr.io/${{ github.repository }}
  tags:
    description: ''
    required: false
    default: latest
  path:
    description: ''
    required: true
    default: ${{ github.workspace }}
  registry:
    description: ''
    required: false
    default: ghcr.io
  registry_username:
    description: ''
    required: false
    default: ${{ github.actor }}
  registry_password:
    description: ''
    required: false
    default: ${{ github.token }}
  build_arguments:
    description: ''
    required: false
    default: ''
outputs:
  digest:
    description: ''
    value: ${{ steps.build.outputs.digest }}
runs:
  using: composite
  steps:
    - run: echo "TAGS=$(for T in ${{ inputs.tags }}; do printf "${{ inputs.repository }}:${T},"; done)" | tee -a $GITHUB_ENV
      shell: bash
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - uses: actions/cache@v3
      with:
        path: /tmp/cache
        key: ${{ inputs.repository }}-buildx
    - uses: docker/build-push-action@v3
      id: build
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ env.TAGS }}
        cache-from: type=local,src=/tmp/cache
        cache-to: type=local,mode=max,dest=/tmp/cache-new
        build-args: ${{ inputs.build_arguments }}
    - run: rm -rf /tmp/cache && mv /tmp/cache-new /tmp/cache
      shell: bash
      